# Generated by Django 4.2.4 on 2023-08-17 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('JobId', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('SocietyId', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('jobId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.job')),
                ('societyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.society')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('GroupeId', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.ManyToManyField(to='app1.user')),
            ],
        ),
    ]
